stages:
  - lint
  - test
  - build
  - deploy
  # - migrate

default:
  tags:
    - orange-pi-5-4gb

lint:
  when: manual
  script:
    - docker run --rm -v $(pwd):/app -w /app golang:1.25-alpine sh -c "go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2 && cd /app/internal && golangci-lint run -c /app/.golangci.yml"

test:
  script:
    - docker run --rm -v $(pwd)/internal:/app -w /app golang:1.25-alpine sh -c "go test ./..."

build:
  when: on_success
  script:
    - docker compose build

deploy:
  when: on_success
  script:
    - docker compose up -d --build


# migrate:
#   stage: migrate

#   script:
#     - make migrate-up config=user
#     - make migrate-up config=video