stages:
  - test
  # - migrate
  - build
  - deploy

default:
  tags:
    - orange-pi-5-4gb

test:
  script:
    - docker run --rm -v $(pwd)/internal:/app -w /app golang:1.25-alpine sh -c "go test ./..."

# migrate:
#   stage: migrate

#   script:
#     - make migrate-up config=user
#     - make migrate-up config=video

build:
  stage: build

  script:
    - docker compose build

deploy:
  stage: deploy

  script:
    - docker compose up -d --build