version: "2"

run:
  tests: false
  relative-path-mode: gomod

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - rowserrcheck
    - gocyclo
    - gocritic
    - misspell
    - lll
    - whitespace
    - unparam
    - gosec
    - nilnesserr
    - sqlclosecheck
    - loggercheck
    - testpackage
    - unconvert
    - gochecknoinits
    - gomoddirectives
    - testableexamples
    - nakedret
    - asciicheck

  settings:
    lll:
      line-length: 120

    gosec:
      severity: high

    whitespace:
      multi-if: true

  exclusions:
    generated: lax
    paths:
      - internal/video-service/docs/.* 
      - internal/user-service/docs/.*

formatters:
  enable:
    - gofmt
    - goimports
    - golines

  exclusions:
    generated: lax
    paths:
      - internal/video-service/docs/.*
      - internal/user-service/docs/.*

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
