// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int64
	Name         string
	Lastname     string
	Email        string
	PasswordHash string
	PasswordSalt string
	CreatedAt    pgtype.Timestamp
	Status       string
	IsAdmin      bool
}
