// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        uuid.UUID
	Name      string
	Lastname  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	Status    string
	IsAdmin   bool
}
