// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, lastname, email, password_hash, password_salt, created_at, status, is_admin)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateUserParams struct {
	Name         string
	Lastname     string
	Email        string
	PasswordHash string
	PasswordSalt string
	CreatedAt    pgtype.Timestamp
	Status       string
	IsAdmin      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Lastname,
		arg.Email,
		arg.PasswordHash,
		arg.PasswordSalt,
		arg.CreatedAt,
		arg.Status,
		arg.IsAdmin,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, lastname, email, password_hash, password_salt, created_at, status, is_admin
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lastname,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.Status,
		&i.IsAdmin,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, lastname, email, password_hash, password_salt, created_at, status, is_admin
FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lastname,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.Status,
		&i.IsAdmin,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = $2, lastname = $3, email = $4, password_hash = $5, password_salt = $6, status = $7, is_admin = $8
WHERE id = $1
`

type UpdateUserParams struct {
	ID           uuid.UUID
	Name         string
	Lastname     string
	Email        string
	PasswordHash string
	PasswordSalt string
	Status       string
	IsAdmin      bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Lastname,
		arg.Email,
		arg.PasswordHash,
		arg.PasswordSalt,
		arg.Status,
		arg.IsAdmin,
	)
	return err
}
