// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, lastname, email, password, created_at, status, is_admin)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateUserParams struct {
	Name      string
	Lastname  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	Status    string
	IsAdmin   bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Lastname,
		arg.Email,
		arg.Password,
		arg.CreatedAt,
		arg.Status,
		arg.IsAdmin,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, name, lastname, email, created_at, status, is_admin
FROM users
WHERE email = $1
`

type FindUserByEmailRow struct {
	ID        uuid.UUID
	Name      string
	Lastname  string
	Email     string
	CreatedAt pgtype.Timestamp
	Status    string
	IsAdmin   bool
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.Status,
		&i.IsAdmin,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT id, name, lastname, email, created_at, status, is_admin
FROM users
WHERE id = $1
`

type FindUserByIdRow struct {
	ID        uuid.UUID
	Name      string
	Lastname  string
	Email     string
	CreatedAt pgtype.Timestamp
	Status    string
	IsAdmin   bool
}

func (q *Queries) FindUserById(ctx context.Context, id uuid.UUID) (FindUserByIdRow, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i FindUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lastname,
		&i.Email,
		&i.CreatedAt,
		&i.Status,
		&i.IsAdmin,
	)
	return i, err
}

const getPassword = `-- name: GetPassword :one
SELECT id, password
FROM users  
WHERE email = $1
`

type GetPasswordRow struct {
	ID       uuid.UUID
	Password string
}

func (q *Queries) GetPassword(ctx context.Context, email string) (GetPasswordRow, error) {
	row := q.db.QueryRow(ctx, getPassword, email)
	var i GetPasswordRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = $2, lastname = $3, email = $4, status = $5, is_admin = $6
WHERE id = $1
`

type UpdateUserParams struct {
	ID       uuid.UUID
	Name     string
	Lastname string
	Email    string
	Status   string
	IsAdmin  bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Lastname,
		arg.Email,
		arg.Status,
		arg.IsAdmin,
	)
	return err
}
