version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - errorlint
    - revive
  settings:
    revive:
      rules:
        - name: var-naming
        - name: line-length-limit
          arguments:
            - 120
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
