// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/ports/id_gen.go

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	reflect "reflect"
	domain "video-provider/internal/video-service/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockIDGen is a mock of IDGen interface.
type MockIDGen struct {
	ctrl     *gomock.Controller
	recorder *MockIDGenMockRecorder
}

// MockIDGenMockRecorder is the mock recorder for MockIDGen.
type MockIDGenMockRecorder struct {
	mock *MockIDGen
}

// NewMockIDGen creates a new mock instance.
func NewMockIDGen(ctrl *gomock.Controller) *MockIDGen {
	mock := &MockIDGen{ctrl: ctrl}
	mock.recorder = &MockIDGenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDGen) EXPECT() *MockIDGenMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDGen) NewID() domain.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(domain.UUID)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDGenMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDGen)(nil).NewID))
}

// Parse mocks base method.
func (m *MockIDGen) Parse(s string) (domain.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", s)
	ret0, _ := ret[0].(domain.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockIDGenMockRecorder) Parse(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockIDGen)(nil).Parse), s)
}
