// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/video-service/ports/video_repo.go

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	context "context"
	reflect "reflect"
	domain "video-provider/video-service/domain"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockVideoRepository is a mock of VideoRepository interface.
type MockVideoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVideoRepositoryMockRecorder
}

// MockVideoRepositoryMockRecorder is the mock recorder for MockVideoRepository.
type MockVideoRepositoryMockRecorder struct {
	mock *MockVideoRepository
}

// NewMockVideoRepository creates a new mock instance.
func NewMockVideoRepository(ctrl *gomock.Controller) *MockVideoRepository {
	mock := &MockVideoRepository{ctrl: ctrl}
	mock.recorder = &MockVideoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoRepository) EXPECT() *MockVideoRepositoryMockRecorder {
	return m.recorder
}

// CreateVideo mocks base method.
func (m *MockVideoRepository) CreateVideo(ctx context.Context, video domain.Video) (domain.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVideo", ctx, video)
	ret0, _ := ret[0].(domain.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVideo indicates an expected call of CreateVideo.
func (mr *MockVideoRepositoryMockRecorder) CreateVideo(ctx, video interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVideo", reflect.TypeOf((*MockVideoRepository)(nil).CreateVideo), ctx, video)
}

// GetPublisherVideos mocks base method.
func (m *MockVideoRepository) GetPublisherVideos(ctx context.Context, publisherID uuid.UUID, params domain.VideoPageParams) ([]domain.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublisherVideos", ctx, publisherID, params)
	ret0, _ := ret[0].([]domain.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublisherVideos indicates an expected call of GetPublisherVideos.
func (mr *MockVideoRepositoryMockRecorder) GetPublisherVideos(ctx, publisherID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublisherVideos", reflect.TypeOf((*MockVideoRepository)(nil).GetPublisherVideos), ctx, publisherID, params)
}

// GetVideoByID mocks base method.
func (m *MockVideoRepository) GetVideoByID(ctx context.Context, id uuid.UUID) (domain.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideoByID", ctx, id)
	ret0, _ := ret[0].(domain.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideoByID indicates an expected call of GetVideoByID.
func (mr *MockVideoRepositoryMockRecorder) GetVideoByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoByID", reflect.TypeOf((*MockVideoRepository)(nil).GetVideoByID), ctx, id)
}

// SearchGlobal mocks base method.
func (m *MockVideoRepository) SearchGlobal(ctx context.Context, query string, params domain.VideoPageParams) ([]domain.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchGlobal", ctx, query, params)
	ret0, _ := ret[0].([]domain.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchGlobal indicates an expected call of SearchGlobal.
func (mr *MockVideoRepositoryMockRecorder) SearchGlobal(ctx, query, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchGlobal", reflect.TypeOf((*MockVideoRepository)(nil).SearchGlobal), ctx, query, params)
}

// SearchPublisher mocks base method.
func (m *MockVideoRepository) SearchPublisher(ctx context.Context, publisherID uuid.UUID, query string, params domain.VideoPageParams) ([]domain.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPublisher", ctx, publisherID, query, params)
	ret0, _ := ret[0].([]domain.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPublisher indicates an expected call of SearchPublisher.
func (mr *MockVideoRepositoryMockRecorder) SearchPublisher(ctx, publisherID, query, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPublisher", reflect.TypeOf((*MockVideoRepository)(nil).SearchPublisher), ctx, publisherID, query, params)
}
