api:
  name: user-service
  host: 127.0.0.1
  port: 8081

db:
  name: user-store
  host: 127.0.0.1
  port: 5433
  maxconns: 30
  vendor: postgres
  version: 18-alpine
  migrationdir: "internal/user-service/adapters/postgres/sql/migrations"
  # used by the service to connect to the database
  url: "$1://$2:$3@$4:$5/$6?sslmode=disable&pool_max_conns=$7&pool_max_conn_lifetime=1h30m"