api:
  name: user-service
  host: 127.0.0.1
  port: 8081

db:
  name: user-store
  host: 127.0.0.1
  port: 5433
  maxconns: 30
  vendor: postgres
  version: 18-alpine
  migrationdir: "internal/user-service/adapters/postgres/sql/migrations"