api:
  name: video-service
  host: 127.0.0.1
  port: 8080

db:
  name: video-store
  host: 127.0.0.1
  port: 5432
  maxconns: 30
  vendor: postgres
  version: 18-alpine
  migrationdir: "internal/video-service/adapters/postgres/sql/migrations"
  