// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/video-service/app/video_service.go

// Package mock_app is a generated GoMock package.
package mock_app

import (
	context "context"
	reflect "reflect"
	domain "video-provider/internal/video-service/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockVideoService is a mock of VideoService interface.
type MockVideoService struct {
	ctrl     *gomock.Controller
	recorder *MockVideoServiceMockRecorder
}

// MockVideoServiceMockRecorder is the mock recorder for MockVideoService.
type MockVideoServiceMockRecorder struct {
	mock *MockVideoService
}

// NewMockVideoService creates a new mock instance.
func NewMockVideoService(ctrl *gomock.Controller) *MockVideoService {
	mock := &MockVideoService{ctrl: ctrl}
	mock.recorder = &MockVideoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoService) EXPECT() *MockVideoServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVideoService) Create(ctx context.Context, video domain.Video) (domain.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, video)
	ret0, _ := ret[0].(domain.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVideoServiceMockRecorder) Create(ctx, video interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVideoService)(nil).Create), ctx, video)
}

// GetByID mocks base method.
func (m *MockVideoService) GetByID(ctx context.Context, videoID domain.UUID) (domain.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, videoID)
	ret0, _ := ret[0].(domain.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockVideoServiceMockRecorder) GetByID(ctx, videoID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockVideoService)(nil).GetByID), ctx, videoID)
}

// GetByPublisher mocks base method.
func (m *MockVideoService) GetByPublisher(ctx context.Context, publisherID domain.UUID, offset, limit int32) ([]domain.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPublisher", ctx, publisherID, offset, limit)
	ret0, _ := ret[0].([]domain.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPublisher indicates an expected call of GetByPublisher.
func (mr *MockVideoServiceMockRecorder) GetByPublisher(ctx, publisherID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPublisher", reflect.TypeOf((*MockVideoService)(nil).GetByPublisher), ctx, publisherID, offset, limit)
}

// SearchGlobal mocks base method.
func (m *MockVideoService) SearchGlobal(ctx context.Context, query string, offset, limit int32) ([]domain.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchGlobal", ctx, query, offset, limit)
	ret0, _ := ret[0].([]domain.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchGlobal indicates an expected call of SearchGlobal.
func (mr *MockVideoServiceMockRecorder) SearchGlobal(ctx, query, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchGlobal", reflect.TypeOf((*MockVideoService)(nil).SearchGlobal), ctx, query, offset, limit)
}

// SearchPublisher mocks base method.
func (m *MockVideoService) SearchPublisher(ctx context.Context, publisherID domain.UUID, query string, offset, limit int32) ([]domain.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPublisher", ctx, publisherID, query, offset, limit)
	ret0, _ := ret[0].([]domain.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPublisher indicates an expected call of SearchPublisher.
func (mr *MockVideoServiceMockRecorder) SearchPublisher(ctx, publisherID, query, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPublisher", reflect.TypeOf((*MockVideoService)(nil).SearchPublisher), ctx, publisherID, query, offset, limit)
}
