basePath: /
definitions:
  httpadp.authResponse:
    properties:
      token:
        type: string
    type: object
  httpadp.createUserRequest:
    properties:
      email:
        type: string
      lastname:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - lastname
    - name
    - password
    type: object
  httpadp.createVideoRequestBody:
    properties:
      description:
        type: string
      topic:
        type: string
    required:
    - description
    - topic
    type: object
  httpadp.loginUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  httpadp.videoResponseBody:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      publisherID:
        type: string
      topic:
        type: string
    type: object
  video-provider_internal_user-service_adapters_http.serviceErrorResponse:
    properties:
      msg:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: Service for managing users.
  title: User Service API
  version: "1.0"
paths:
  /v1/users:
    post:
      consumes:
      - application/json
      description: Creates a new user and return the created user's ID. Example ID
      parameters:
      - description: CreateUser user payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/httpadp.createUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 'created user id (example: 123e4567-e89b-12d3-a456-426614174000)'
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/video-provider_internal_user-service_adapters_http.serviceErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/video-provider_internal_user-service_adapters_http.serviceErrorResponse'
      summary: Creates a new user
      tags:
      - Users
  /v1/users/{id}:
    get:
      description: Retrieve user details by ID. The ID can be provided as a
      parameters:
      - description: 'User ID (example: 123e4567-e89b-12d3-a456-426614174000)'
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/video-provider_internal_user-service_adapters_http.serviceErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/video-provider_internal_user-service_adapters_http.serviceErrorResponse'
      summary: Get user by ID
      tags:
      - Users
  /v1/users/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a JWT token
      parameters:
      - description: Login user payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/httpadp.loginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpadp.authResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/video-provider_internal_user-service_adapters_http.serviceErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/video-provider_internal_user-service_adapters_http.serviceErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/video-provider_internal_user-service_adapters_http.serviceErrorResponse'
      summary: User login
      tags:
      - Users
  /v1/videos/id/{videoID}:
    get:
      description: Returns details of a single video by its unique identifier
      parameters:
      - description: video ID (UUID)
        format: uuid
        in: path
        name: videoID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpadp.videoResponseBody'
        "400":
          description: Invalid video ID format
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get video by ID
      tags:
      - videos
  /v1/videos/pub/{publisherID}:
    get:
      description: Returns a list of videos for a specific publisher with pagination
        and search support
      parameters:
      - description: publisher ID (UUID)
        in: path
        name: publisherID
        required: true
        type: string
      - description: 'Limit (example: 10)'
        in: query
        name: limit
        type: integer
      - description: 'Offset (example: 0)'
        in: query
        name: offset
        type: integer
      - description: 'Sort (example: `date`)'
        in: query
        name: sort
        type: string
      - description: 'Order (asc or desc, example: `t` for ascending, `f` for descending)'
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/httpadp.videoResponseBody'
            type: array
      summary: Get videos by publisher
      tags:
      - videos
    post:
      consumes:
      - application/json
      description: Creates a new video record for the specified publisher.
      parameters:
      - description: Publisher ID (UUID)
        in: path
        name: publisherID
        required: true
        type: string
      - description: Video creation request body
        in: body
        name: video
        required: true
        schema:
          $ref: '#/definitions/httpadp.createVideoRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Creates new video.
      tags:
      - videos
  /v1/videos/search/:
    get:
      description: Search videos in the entire database by a keyword
      parameters:
      - description: Search query
        in: query
        name: query
        required: true
        type: string
      - description: 'Limit (example: 10)'
        in: query
        name: limit
        type: integer
      - description: 'Offset (example: 0)'
        in: query
        name: offset
        type: integer
      - description: 'Sort (example: `date`)'
        in: query
        name: sort
        type: string
      - description: 'Order (asc or desc, example: `t` for ascending, `f` for descending)'
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/httpadp.videoResponseBody'
            type: array
      summary: Global search
      tags:
      - videos
swagger: "2.0"
