// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID          uuid.UUID
	Publisherid uuid.UUID
	Comment     string
	Createdat   pgtype.Time
	Status      pgtype.Text
}

type Video struct {
	ID          uuid.UUID
	Publisherid uuid.UUID
	Topic       string
	Description pgtype.Text
	Createdat   pgtype.Time
	Status      pgtype.Text
}
