// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	GetLatestTopNUploads(ctx context.Context, limit int32) ([]Video, error)
	GetVideoByID(ctx context.Context, id uuid.UUID) (Video, error)
	GetVideosByPublisher(ctx context.Context, arg GetVideosByPublisherParams) ([]Video, error)
	SearchGlobal(ctx context.Context, arg SearchGlobalParams) ([]Video, error)
	SearchPublisher(ctx context.Context, arg SearchPublisherParams) ([]Video, error)
	UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error)
}

var _ Querier = (*Queries)(nil)
