// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
  publisherid, topic, description, createdAt
) VALUES (
  $1, $2, $3, NOW()
)
RETURNING id, publisherid, topic, description, createdat, status
`

type CreateVideoParams struct {
	Publisherid uuid.UUID
	Topic       string
	Description pgtype.Text
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo, arg.Publisherid, arg.Topic, arg.Description)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Publisherid,
		&i.Topic,
		&i.Description,
		&i.Createdat,
		&i.Status,
	)
	return i, err
}

const getLatestTopNUploads = `-- name: GetLatestTopNUploads :many
SELECT id, publisherid, topic, description, createdat, status FROM videos ORDER BY createdAt DESC LIMIT $1
`

func (q *Queries) GetLatestTopNUploads(ctx context.Context, limit int32) ([]Video, error) {
	rows, err := q.db.Query(ctx, getLatestTopNUploads, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Publisherid,
			&i.Topic,
			&i.Description,
			&i.Createdat,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, publisherid, topic, description, createdat, status FROM videos WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVideoByID(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Publisherid,
		&i.Topic,
		&i.Description,
		&i.Createdat,
		&i.Status,
	)
	return i, err
}

const getVideosByPublisher = `-- name: GetVideosByPublisher :many
SELECT id, publisherid, topic, description, createdat, status FROM videos WHERE publisherid = $1 ORDER BY createdAt LIMIT $2 OFFSET $3
`

type GetVideosByPublisherParams struct {
	Publisherid uuid.UUID
	Limit       int32
	Offset      int32
}

func (q *Queries) GetVideosByPublisher(ctx context.Context, arg GetVideosByPublisherParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, getVideosByPublisher, arg.Publisherid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Publisherid,
			&i.Topic,
			&i.Description,
			&i.Createdat,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGlobal = `-- name: SearchGlobal :many
SELECT id, publisherid, topic, description, createdat, status FROM videos WHERE topic LIKE CONCAT('%', $1, '%') OR description LIKE CONCAT('%', $1, '%') ORDER BY createdAt LIMIT $2 OFFSET $3
`

type SearchGlobalParams struct {
	Concat interface{}
	Limit  int32
	Offset int32
}

func (q *Queries) SearchGlobal(ctx context.Context, arg SearchGlobalParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, searchGlobal, arg.Concat, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Publisherid,
			&i.Topic,
			&i.Description,
			&i.Createdat,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPublisher = `-- name: SearchPublisher :many
SELECT id, publisherid, topic, description, createdat, status FROM videos WHERE publisherid = $1 AND (topic LIKE CONCAT('%', $2, '%') OR description LIKE CONCAT('%', $2, '%')) ORDER BY createdAt LIMIT $3 OFFSET $4
`

type SearchPublisherParams struct {
	Publisherid uuid.UUID
	Concat      interface{}
	Limit       int32
	Offset      int32
}

func (q *Queries) SearchPublisher(ctx context.Context, arg SearchPublisherParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, searchPublisher,
		arg.Publisherid,
		arg.Concat,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Publisherid,
			&i.Topic,
			&i.Description,
			&i.Createdat,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideo = `-- name: UpdateVideo :one
UPDATE videos SET
  topic = $2,
  description = $3,
  updatedAt = NOW()
WHERE id = $1
RETURNING id, publisherid, topic, description, createdat, status
`

type UpdateVideoParams struct {
	ID          uuid.UUID
	Topic       string
	Description pgtype.Text
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideo, arg.ID, arg.Topic, arg.Description)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Publisherid,
		&i.Topic,
		&i.Description,
		&i.Createdat,
		&i.Status,
	)
	return i, err
}
